  version: 2
  updates:
  - package-ecosystem: "gradle"
    directory: "/build.gradle"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Budapest"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Budapest"
