  version: 2
  updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Budapest"
  - package-ecosystem: "gradle"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Budapest"
    ignore:
    - dependency-name: "*"
  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Budapest"
